### ISSUE TITLE
Make it possible to configure the resource allocations of the processor

### ISSUE THREAD

**Issue by CalebTVanDyke** [launchflow/buildflow#113]
Right now we default to .5 CPUs, we should have a way for users to specify the resource requirements (e.g. cpu / gpu)

**Comment by aeroaks** [comment]
From looking at the code, I see that `@flow.processor` already use `num_cpus` (https://github.com/launchflow/buildflow/blob/main/buildflow/runtime/flow.py#L37). Is there something more to this issue?

**Comment by CalebTVanDyke** [comment]
Nope should be all working now! Just forgot to close the issue.

This was included with #133  and release v0.0.14
