### ISSUE TITLE
add sink for clickhouse

### ISSUE THREAD

**Issue by boetro** [launchflow/buildflow#209]

**Comment by roopeshsn** [comment]
Hi, @boetro! I would like to work on this issue! I would start with adding `io` for clickhouse and figuring out from there would make sense.

**Comment by boetro** [comment]
SG! I went ahead and assigned it to you, feel free to ask in questions in here or on discord!

**Comment by roopeshsn** [comment]
Hi, @boetro! There are two options to proceed with:

1. Unlike the DuckDB, the Clickhouse isn't an in-memory solution meaning it requires a server. Clickhouse python client doesn't create an instance of a server when using the [get_client](https://clickhouse.com/docs/en/integrations/python#establish-a-connection) method. So it requires manual effort to set up the clickhouse server from the [downloads](https://clickhouse.com/#getting_started) page.
2. The second option is to create an instance of a server programmatically through Docker or using shell scripts to download and install clickhouse server from the [downloads](https://clickhouse.com/#getting_started) page if not present already.

Which option should I proceed with? I would like to hear your thoughts!

**Comment by roopeshsn** [comment]
Hi @boetro! Apart from creating a table, I am done with all other implementations. I am not able to create a table with attributes (schema) dynamically from a dictionary or a df through [clickhouse python client](https://clickhouse.com/docs/en/integrations/python). The equivalent query I found in the DuckDB strategies is this, `con.execute(f'CREATE TABLE "{self.table}" AS SELECT * FROM df')`.

I reached out to the clickhouse community (slack) with my query but didn't get help. Do you know any workaround?

**Comment by boetro** [comment]
I think it's fine if the table isn't dynamically created, and it assumes the user would have created it.

DuckDB is kind of the exception here, our other dataware house like sinks (snowflake and bigquery) assume the user has created it (but do provide the pulumi option for creating them).
